# This is a basic workflow that is manually triggered

name: Generate Docs

env:
  version_joined: ''
  doxygen_path: sig-docs-community/tools/o3de-doxygen

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (xx.yy.z)'
        required: true
        type: string

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Get Version w/o dots
        run: INPUT=${{ inputs.version }}; echo "version_joined=${INPUT//./}" >> ${GITHUB_ENV}

      - name: Checkout api.o3de.org
        uses: actions/checkout@v4.2.2
        with:
          path: api.o3de.org
          repository: o3de/api.o3de.org
          # Grab the main branch
          ref: main

      - name: Sanity check
        run: ls -la ${{ github.workspace }}

      - name: Checkout O3DE
        uses: actions/checkout@v4.2.2
        with:
          path: o3de
          repository: o3de/o3de
          # Grab the stabilization branch
          ref: "stabilization/${{ env.version_joined }}"
      - name: Checkout O3DE-extras
        uses: actions/checkout@v4.2.2
        with:
          path: o3de-extras
          repository: o3de/o3de-extras
          # Grab the stabilization branch
          ref: "stabilization/${{ env.version_joined }}"
      - name: Checkout sig-docs
        uses: actions/checkout@v4.2.2
        with:
          path: sig-docs-community
          repository: o3de/sig-docs-community
          # Grab the main branch
          ref: main

      - name: Set config
        # Set the config information
        run: |
          echo "#! /bin/bash \n\nO3DE_PATH=${{ github.workspace }}/o3de \nO3DEORG_PATH=${{ github.workspace }}/api.o3de.org \nPROJECT_NUMBER=${{ inputs.version }}" > ${{ env.doxygen_path }}/config.sh
      - name: Move to Doxygen path
        run: cd ${{ github.workspace}}/${{ env.doxygen_path }}
      - name: Ensure scripts are executable
        run: chmod +x *.sh
      - name: Copy extras Gems
        run: cp -r ${{ github.workspace }}/o3de-extras/Gems/* ${{ github.workspace }}/o3de/Gems
      - name: Generate Framework
        run: ./o3de-framework-apis.sh
      - name: Generate Gems
        run: ./o3de-framework-gems.sh
      - name: Commit and Create PR
        uses: peter-evans/create-pull-request@v7
        with:
          signoff: true
          commit-message: "Automatic generation of API docs for version ${{ inputs.version }}."
          branch: generate/${{ inputs.version }}
          title: "Generate API docs for ${{ inputs.version }}"
          body: "Automated change from ${{ github.action }} GitHub Action."
  